version: '3.8'

services:
  app:
    build: ./connector
    ports:
      - "5000:8090"  # Adjust if your app uses a different port
    depends_on:
      - db
    networks:
      - my-bridge-network
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-bridge-network

  pgadmin:
    container_name: admin_container
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my-bridge-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - my-bridge-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - my-bridge-network



volumes:
  postgres_data:

networks:
  my-bridge-network:
    driver: bridge