version: "3.8"

services:
  connector:
    container_name: connector_container
    build: .
    volumes:
      - .:/code
    ports:
      - 8090:8090
    depends_on:
      - db
    command:
      - python3 ./frontend_AI_connector.py
  db:
    container_name: db_container
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    container_name: admin_container
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data: